#!/usr/bin/env python3
"""
Telegram Bot Setup Helper
=========================
Helps you create a Telegram bot and get your chat_id.

This script:
1. Guides you through creating a bot via @BotFather (manual step)
2. Automatically gets your chat_id after you message the bot
3. Saves credentials to config.env

Usage:
    python setup_telegram.py
    python setup_telegram.py --token YOUR_BOT_TOKEN  # If you already have a token
"""

import os
import sys
import time
import argparse
from pathlib import Path

try:
    import requests
except ImportError:
    print("Installing requests...")
    os.system(f"{sys.executable} -m pip install requests")
    import requests


def get_bot_info(token: str) -> dict:
    """Get bot information from Telegram API."""
    url = f"https://api.telegram.org/bot{token}/getMe"
    resp = requests.get(url, timeout=10)
    if resp.status_code == 200:
        return resp.json().get("result", {})
    return {}


def get_updates(token: str) -> list:
    """Get recent messages to the bot."""
    url = f"https://api.telegram.org/bot{token}/getUpdates"
    resp = requests.get(url, timeout=10)
    if resp.status_code == 200:
        return resp.json().get("result", [])
    return []


def send_test_message(token: str, chat_id: str) -> bool:
    """Send a test message to verify the setup."""
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": "🎉 *QJ Security Check* connected successfully!\n\nYou will receive security alerts here.",
        "parse_mode": "Markdown"
    }
    resp = requests.post(url, json=payload, timeout=10)
    return resp.status_code == 200


def save_config(token: str, chat_id: str):
    """Save credentials to config.env."""
    config_path = Path(__file__).parent / "config.env"
    
    # Read existing config if present
    existing = {}
    if config_path.exists():
        with open(config_path) as f:
            for line in f:
                if "=" in line and not line.strip().startswith("#"):
                    key, _, val = line.partition("=")
                    existing[key.strip()] = val.strip()
    
    # Update with new values
    existing["TELEGRAM_BOT_TOKEN"] = f'"{token}"'
    existing["TELEGRAM_CHAT_ID"] = f'"{chat_id}"'
    
    # Write back
    with open(config_path, "w") as f:
        f.write("# QJ Security Check - Configuration\n")
        f.write("# Auto-generated by setup_telegram.py\n\n")
        f.write("# Telegram\n")
        f.write(f"TELEGRAM_BOT_TOKEN={existing['TELEGRAM_BOT_TOKEN']}\n")
        f.write(f"TELEGRAM_CHAT_ID={existing['TELEGRAM_CHAT_ID']}\n")
        f.write("\n")
        
        # Write other existing vars
        for key, val in existing.items():
            if key not in ("TELEGRAM_BOT_TOKEN", "TELEGRAM_CHAT_ID"):
                f.write(f"{key}={val}\n")
    
    print(f"\n✓ Saved to {config_path}")


def create_bot_interactive():
    """Interactive bot creation wizard."""
    print("""
╔══════════════════════════════════════════════════════════════════╗
║           🤖 Telegram Bot Setup for QJ Security Check            ║
╚══════════════════════════════════════════════════════════════════╝

This will help you:
1. Create a Telegram bot (via @BotFather)
2. Get your chat_id automatically
3. Save credentials for security alerts

""")
    
    print("=" * 60)
    print("STEP 1: Create a bot via @BotFather")
    print("=" * 60)
    print("""
1. Open Telegram and search for: @BotFather
2. Send: /newbot
3. Choose a NAME for your bot (e.g., "QJ Security Alerts")
4. Choose a USERNAME ending in 'bot' (e.g., "qj_security_bot")
5. Copy the API token that BotFather gives you

The token looks like: 1234567890:ABCDefgh-ijklmnop_qrstuvwxyz
""")
    
    token = input("\nPaste your bot token here: ").strip()
    
    if not token or ":" not in token:
        print("❌ Invalid token format. Should contain ':'")
        return
    
    # Verify token
    print("\nVerifying token...")
    bot_info = get_bot_info(token)
    
    if not bot_info:
        print("❌ Invalid token or API error")
        return
    
    bot_name = bot_info.get("first_name", "Unknown")
    bot_username = bot_info.get("username", "unknown")
    print(f"✓ Bot verified: {bot_name} (@{bot_username})")
    
    print("\n" + "=" * 60)
    print("STEP 2: Get your chat_id")
    print("=" * 60)
    print(f"""
Now I need your chat_id. Here's how:

1. Open Telegram
2. Search for your bot: @{bot_username}
3. Click START or send any message to it
4. Come back here and press ENTER

I'll automatically detect your chat_id.
""")
    
    input("Press ENTER after you've messaged the bot...")
    
    # Poll for updates
    print("\nLooking for your message...")
    chat_id = None
    
    for attempt in range(5):
        updates = get_updates(token)
        
        for update in updates:
            msg = update.get("message", {})
            chat = msg.get("chat", {})
            if chat.get("id"):
                chat_id = str(chat["id"])
                chat_type = chat.get("type", "unknown")
                chat_name = chat.get("first_name", "") or chat.get("title", "Unknown")
                print(f"✓ Found chat: {chat_name} (type: {chat_type})")
                break
        
        if chat_id:
            break
        
        print(f"  Waiting... (attempt {attempt + 1}/5)")
        time.sleep(2)
    
    if not chat_id:
        print("\n❌ Could not find your chat_id.")
        print("Please enter it manually.")
        print("\nTo find it manually:")
        print(f"  1. Visit: https://api.telegram.org/bot{token}/getUpdates")
        print("  2. Look for: \"chat\":{\"id\":XXXXXXXX")
        chat_id = input("\nEnter your chat_id: ").strip()
    
    if not chat_id:
        print("❌ No chat_id provided")
        return
    
    print("\n" + "=" * 60)
    print("STEP 3: Test and save")
    print("=" * 60)
    
    print("\nSending test message...")
    if send_test_message(token, chat_id):
        print("✓ Test message sent! Check your Telegram.")
    else:
        print("⚠ Test message failed, but credentials might still work.")
    
    # Save config
    save_config(token, chat_id)
    
    print("\n" + "=" * 60)
    print("✅ SETUP COMPLETE!")
    print("=" * 60)
    print(f"""
Your bot is ready:
  • Bot: @{bot_username}
  • Chat ID: {chat_id}
  • Config: ./config.env

To test sending alerts:
  python notify_py.py --test

To enable hourly checks with alerts:
  ./install_cron.sh
""")


def setup_with_token(token: str):
    """Setup using existing token."""
    print(f"Using provided token...")
    
    bot_info = get_bot_info(token)
    if not bot_info:
        print("❌ Invalid token")
        return
    
    bot_username = bot_info.get("username", "unknown")
    print(f"✓ Bot: @{bot_username}")
    
    print("\nFetching recent messages...")
    updates = get_updates(token)
    
    chats = {}
    for update in updates:
        msg = update.get("message", {})
        chat = msg.get("chat", {})
        if chat.get("id"):
            cid = str(chat["id"])
            name = chat.get("first_name", "") or chat.get("title", f"Chat {cid}")
            chats[cid] = name
    
    if not chats:
        print("No chats found. Send a message to your bot first.")
        print(f"\n  1. Open Telegram and search for @{bot_username}")
        print("  2. Send any message")
        print("  3. Run this script again")
        return
    
    print("\nFound chats:")
    for i, (cid, name) in enumerate(chats.items(), 1):
        print(f"  {i}. {name} (ID: {cid})")
    
    if len(chats) == 1:
        chat_id = list(chats.keys())[0]
        print(f"\nUsing: {chats[chat_id]}")
    else:
        choice = input("\nSelect chat number: ").strip()
        try:
            idx = int(choice) - 1
            chat_id = list(chats.keys())[idx]
        except (ValueError, IndexError):
            print("Invalid selection")
            return
    
    print("\nSending test...")
    if send_test_message(token, chat_id):
        print("✓ Test message sent!")
    
    save_config(token, chat_id)
    print("\n✅ Done! Run: python notify_py.py --test")


def main():
    parser = argparse.ArgumentParser(description="Setup Telegram bot for QJ Security Check")
    parser.add_argument("--token", type=str, help="Use existing bot token")
    args = parser.parse_args()
    
    if args.token:
        setup_with_token(args.token)
    else:
        create_bot_interactive()


if __name__ == "__main__":
    main()
